In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import joblib

In [5]:
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"

col = ['preg' , 'plas' , 'pres' , 'skin' , 'test', 'pedi' , 'mass' , 'age' , 'Results']

df = pd.read_csv(url , names= col)

df

     preg  plas  pres  skin  test  pedi   mass  age  Results
0       6   148    72    35     0  33.6  0.627   50        1
1       1    85    66    29     0  26.6  0.351   31        0
2       8   183    64     0     0  23.3  0.672   32        1
3       1    89    66    23    94  28.1  0.167   21        0
4       0   137    40    35   168  43.1  2.288   33        1
..    ...   ...   ...   ...   ...   ...    ...  ...      ...
763    10   101    76    48   180  32.9  0.171   63        0
764     2   122    70    27     0  36.8  0.340   27        0
765     5   121    72    23   112  26.2  0.245   30        0
766     1   126    60     0     0  30.1  0.349   47        1
767     1    93    70    31     0  30.4  0.315   23        0

[768 rows x 9 columns]

In [7]:
x = df.iloc[: , 0:8]

x

     preg  plas  pres  skin  test  pedi   mass  age
0       6   148    72    35     0  33.6  0.627   50
1       1    85    66    29     0  26.6  0.351   31
2       8   183    64     0     0  23.3  0.672   32
3       1    89    66    23    94  28.1  0.167   21
4       0   137    40    35   168  43.1  2.288   33
..    ...   ...   ...   ...   ...   ...    ...  ...
763    10   101    76    48   180  32.9  0.171   63
764     2   122    70    27     0  36.8  0.340   27
765     5   121    72    23   112  26.2  0.245   30
766     1   126    60     0     0  30.1  0.349   47
767     1    93    70    31     0  30.4  0.315   23

[768 rows x 8 columns]

In [8]:
y = df.iloc[: , -1]

y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Results, Length: 768, dtype: int64

In [9]:
X_train , X_test , y_train , Y_test = train_test_split(x,y , test_size=0.2 , random_state= 101)

In [15]:
model = LogisticRegression()
model.fit(X_train , y_train)

joblib.dump(model , 'Log_model.pkl')

C:\Users\Mohammed Israr\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

['Log_model.pkl']

In [11]:
model.predict(X_test)

array([0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1],
      dtype=int64)

In [12]:
model.score(X_test , Y_test)

0.7987012987012987